[package]
name = "sway-status"
version = "0.1.0"
authors = ["Javier Pena Dalúa <javier.pena.dalua@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
